# server
server:
  port: 7090
  context-path: /chat

# spring
spring:
  mvc:
    favicon:
      enabled: false
  http:
    encoding:
      force: true
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .html

# log
logging:
  file: log/chat.log

# origins
allowedOrigins:
  test: http://localhost
  product: http://106.14.200.121


